### ISSUE TITLE
Neko Std.random error

### ISSUE THREAD

**Issue by christopherghenderson** [RudenkoArts/clay#1]
I'm unable to compile with Neko.  Std.Random does not like 0x7fffffff in clay.utils.id.hx.  I think you can use several hundred million without negatively affecting the unique id generation.

> if(val == null) {
> 			**val = Std.random(0x7fffffff);**
> 		}
> 		function to_char(value:Int) : String {
> 			if (value > 9) {
> 				var ascii = (65 + (value - 10));
> 				if (ascii > 90) { ascii += 6; }
> 				return String.fromCharCode(ascii);
> 			} else return Std.string(value).charAt(0);
> 		} //to_char
>  		var r = Std.int(val % 62);
> 		var q = Std.int(val / 62);
> 		if (q > 0) return uniqueid(q) + to_char(r);
> 		else return Std.string(to_char(r));
>  	}

**Comment by RudenkoArts** [comment]
@christopherghenderson thanks!
